name: clickthecity-epg-scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'  # Every 8 hours

permissions:
  contents: write

jobs:
  fetch_epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Let checkout configure auth for pushing
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install requests pytz beautifulsoup4

      - name: Decode and Run CLICKTHECITY EPG fetcher
        env:
          CLICKTHECITY_EPG_FETCHER: ${{ secrets.CLICKTHECITY_EPG_FETCHER }}
        run: |
          echo "$CLICKTHECITY_EPG_FETCHER" | tr -d '\n' | base64 --decode > clickthecity_epg.py
          python clickthecity_epg.py
          rm clickthecity_epg.py

      - name: Commit and push if changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"

          git add *.xml *.xml.gz || true

          git diff --staged --quiet || git commit -m "Update EPG data"
          git push
